/**
 * Casper Group — Brand Constants (Fallback/Offline)
 * These are used when Supabase is not configured.
 * In production, use useBrands() hook from hooks/useSupabaseData.ts
 */
export const BRANDS = [
  {
    id: 'angel-wings',
    name: 'Angel Wings',
    tagline: 'Wings. Shrimps. Fries. Respect the Basket.',
    mascot: 'Loudini the Wing Wizard',
    colors: ['#FFA500', '#FF6347'],
    revenue: '—',
    growth: 0,
    topSeller: '—',
    icon: '🍗',
  },
  {
    id: 'pasta-bish',
    name: 'Pasta Bish',
    tagline: 'Fresh Pasta. Bold Flavor.',
    mascot: 'Noodle Queen',
    colors: ['#DC143C', '#8B0000'],
    revenue: '—',
    growth: 0,
    topSeller: '—',
    icon: '🍝',
  },
  {
    id: 'taco-yaki',
    name: 'Taco Yaki',
    tagline: 'Fire Meets Flavor',
    mascot: 'Baby Panda Chef',
    colors: ['#FF1493', '#FF69B4'],
    revenue: '—',
    growth: 0,
    topSeller: '—',
    icon: '🌮',
  },
  {
    id: 'patty-daddy',
    name: 'Patty Daddy',
    tagline: 'The Sauce Is a Secret, The Flavor Is Not.',
    mascot: 'Paddy Daddy',
    colors: ['#8B4513', '#D2691E'],
    revenue: '—',
    growth: 0,
    topSeller: '—',
    icon: '🍔',
  },
  {
    id: 'espresso-co',
    name: 'Espresso Co.',
    tagline: 'Precision Brewed',
    mascot: 'Beanzo the Barista',
    colors: ['#4B0082', '#8A2BE2'],
    revenue: '—',
    growth: 0,
    topSeller: '—',
    icon: '☕',
  },
  {
    id: 'morning-after',
    name: 'Morning After',
    tagline: 'Brunch All Day',
    mascot: 'Eggavier & Scrambalina',
    colors: ['#FFE4B5', '#FFDEAD'],
    revenue: '—',
    growth: 0,
    topSeller: '—',
    icon: '🍳',
  },
  {
    id: 'tossd',
    name: "Toss'd",
    tagline: 'Fresh Tossed. Always.',
    mascot: 'Leaf Boss',
    colors: ['#228B22', '#32CD32'],
    revenue: '—',
    growth: 0,
    topSeller: '—',
    icon: '🥗',
  },
  {
    id: 'sweet-tooth',
    name: 'Sweet Tooth',
    tagline: 'Sugar Rush Central',
    mascot: 'Sweetness the Cupcake',
    colors: ['#FF69B4', '#FFB6C1'],
    revenue: '—',
    growth: 0,
    topSeller: '—',
    icon: '🧁',
  },
  {
    id: 'mojo-juice',
    name: 'Mojo Juice',
    tagline: 'Tropical Energy',
    mascot: 'Mojo the Mango',
    colors: ['#32CD32', '#00FF00'],
    revenue: '—',
    growth: 0,
    topSeller: '—',
    icon: '🥤',
  },
  {
    id: 'mr-oyster',
    name: 'Mr. Oyster',
    tagline: 'Pearl of the Sea',
    mascot: 'Sir Shellington',
    colors: ['#4682B4', '#5F9EA0'],
    revenue: '—',
    growth: 0,
    topSeller: '—',
    icon: '🦪',
  },
  {
    id: 'peace-pizza',
    name: 'Peace Pizza',
    tagline: 'A Slice of Peace.',
    mascot: 'Peace the Pizza',
    colors: ['#F4A340', '#7A2F22'],
    revenue: '—',
    growth: 0,
    topSeller: '—',
    icon: '🍕',
  },
  {
    id: 'american-dragon',
    name: 'American Dragon',
    tagline: 'Fire-Forged Flavor.',
    mascot: 'The American Dragon',
    colors: ['#D4AF37', '#9B1C1C'],
    revenue: '—',
    growth: 0,
    topSeller: '—',
    icon: '🐉',
  },
];
