export const BRANDS = [
  {
    id: 'angel-wings',
    name: 'ANGEL WINGS',
    tagline: 'Wings. Shrimps. Fries. Respect the Basket.',
    mascot: 'Loudini the Wing Wizard',
    colors: ['#FFA500', '#FF6347'],
    revenue: '$892K',
    growth: 14,
    topSeller: 'Lemon Pepper Wings',
    icon: '🍗',
  },
  {
    id: 'pasta-bish',
    name: 'PASTA BISH',
    tagline: 'Italian Done Right',
    mascot: 'Nonna Rosa',
    colors: ['#8B0000', '#FFD700'],
    revenue: '$1.4M',
    growth: 26,
    topSeller: 'Truffle Carbonara',
    icon: '🍝',
  },
  {
    id: 'taco-yaki',
    name: 'TACO YAKI',
    tagline: 'Fire Meets Flavor',
    mascot: 'Baby Panda Chef',
    colors: ['#FF1493', '#FF69B4'],
    revenue: '$678K',
    growth: 18,
    topSeller: 'Fusion Taco Platter',
    icon: '🌮',
  },
  {
    id: 'patty-daddy',
    name: 'PATTY DADDY',
    tagline: 'The Sauce Is a Secret, The Flavor Is Not.',
    mascot: 'Paddy Daddy',
    colors: ['#8B4513', '#D2691E'],
    revenue: '$1.2M',
    growth: 22,
    topSeller: 'Daddy Deluxe Burger',
    icon: '🍔',
  },
  {
    id: 'espresso-co',
    name: 'ESPRESSO CO',
    tagline: 'Precision Brewed',
    mascot: 'Beanzo the Barista',
    colors: ['#4B0082', '#8A2BE2'],
    revenue: '$342K',
    growth: 28,
    topSeller: 'Double Shot Formula',
    icon: '☕',
  },
  {
    id: 'morning-after',
    name: 'MORNING AFTER',
    tagline: 'Brunch All Day',
    mascot: 'Eggavier & Scrambalina',
    colors: ['#FFE4B5', '#FFDEAD'],
    revenue: '$456K',
    growth: 12,
    topSeller: 'Hangover Helper',
    icon: '🍳',
  },
  {
    id: 'tossd',
    name: "TOSS'D",
    tagline: 'Fresh Salads, Bold Flavors',
    mascot: 'Leafy Larry',
    colors: ['#228B22', '#90EE90'],
    revenue: '$312K',
    growth: 35,
    topSeller: 'Caesar Supreme',
    icon: '🥗',
  },
  {
    id: 'sweet-tooth',
    name: 'SWEET TOOTH',
    tagline: 'Sugar Rush Central',
    mascot: 'Sweetness the Cupcake',
    colors: ['#FF69B4', '#FFB6C1'],
    revenue: '$234K',
    growth: 16,
    topSeller: 'Rainbow Explosion',
    icon: '🧁',
  },
  {
    id: 'mojo-juice',
    name: 'MOJO JUICE',
    tagline: 'Tropical Energy',
    mascot: 'Mojo the Mango',
    colors: ['#32CD32', '#00FF00'],
    revenue: '$289K',
    growth: 31,
    topSeller: 'Mango Madness',
    icon: '🥤',
  },
  {
    id: 'mr-oyster',
    name: 'MR. OYSTER',
    tagline: 'Pearl of the Sea',
    mascot: 'Sir Shellington',
    colors: ['#4682B4', '#5F9EA0'],
    revenue: '$567K',
    growth: 9,
    topSeller: 'Oyster Rockefeller',
    icon: '🦪',
  },
];