export const LOCATIONS = [
  {
    id: 'atlanta',
    name: 'Atlanta',
    x: '48%',
    y: '58%',
    status: 'surge' as const,
    revenue: '$1.8M',
    address: 'Multiple locations, Atlanta GA',
  },
  {
    id: 'houston',
    name: 'Houston',
    x: '35%',
    y: '62%',
    status: 'open' as const,
    revenue: '$1.2M',
    address: 'Multiple locations, Houston TX',
  },
  {
    id: 'las-vegas',
    name: 'Las Vegas',
    x: '15%',
    y: '48%',
    status: 'open' as const,
    revenue: '$2.1M',
    address: 'Multiple locations, Las Vegas NV',
  },
  {
    id: 'washington-dc',
    name: 'Washington DC',
    x: '52%',
    y: '42%',
    status: 'surge' as const,
    revenue: '$1.6M',
    address: 'Multiple locations, Washington DC',
  },
  {
    id: 'charlotte',
    name: 'Charlotte',
    x: '50%',
    y: '54%',
    status: 'open' as const,
    revenue: '$980K',
    address: 'Multiple locations, Charlotte NC',
  },
  {
    id: 'miami',
    name: 'Miami',
    x: '52%',
    y: '68%',
    status: 'open' as const,
    revenue: '$1.4M',
    address: 'Multiple locations, Miami FL',
  },
  {
    id: 'new-york',
    name: 'New York',
    x: '54%',
    y: '36%',
    status: 'surge' as const,
    revenue: '$2.5M',
    address: 'Multiple locations, New York NY',
  },
  {
    id: 'los-angeles',
    name: 'Los Angeles',
    x: '10%',
    y: '52%',
    status: 'open' as const,
    revenue: '$2.2M',
    address: 'Multiple locations, Los Angeles CA',
  },
];