export const BRANDS = [
  {
    id: 'angel-wings',
    name: "Angel Wings",
    tagline: 'Wings. Shrimps. Fries. Respect the Basket.',
    mascot: 'Loudini the Wing Wizard',
    colors: ['#FFA500', '#FF6347'],
    revenue: '$892K',
    growth: 14,
    topSeller: 'Angel Wings',
    icon: '🍗',
  },
  {
    id: 'patty-daddy',
    name: 'Patty Daddy',
    tagline: 'The Sauce Is a Secret, The Flavor Is Not.',
    mascot: 'Paddy Daddy',
    colors: ['#8B4513', '#D2691E'],
    revenue: '$1.2M',
    growth: 22,
    topSeller: 'Daddy Deluxe Burger',
    icon: '🍔',
  },
  {
    id: 'taco-yaki',
    name: 'Taco Yaki',
    tagline: 'Fire Meets Flavor',
    mascot: 'Baby Panda Chef',
    colors: ['#FF1493', '#FF69B4'],
    revenue: '$678K',
    growth: 18,
    topSeller: 'Fusion Taco Platter',
    icon: '🌮',
  },
  {
    id: 'tha-morning-after',
    name: 'Tha Morning After',
    tagline: 'Brunch All Day',
    mascot: 'Eggavier & Scrambalina',
    colors: ['#FFE4B5', '#FFDEAD'],
    revenue: '$456K',
    growth: 12,
    topSeller: 'Hangover Helper',
    icon: '🍳',
  },
  {
    id: 'espresso-co',
    name: 'Espresso Co.',
    tagline: 'Precision Brewed',
    mascot: 'Beanzo the Barista',
    colors: ['#4B0082', '#8A2BE2'],
    revenue: '$342K',
    growth: 28,
    topSeller: 'Double Shot Formula',
    icon: '☕',
  },
  {
    id: 'mojo-juice',
    name: 'Mojo Juice',
    tagline: 'Tropical Energy',
    mascot: 'Mojo the Mango',
    colors: ['#32CD32', '#00FF00'],
    revenue: '$289K',
    growth: 31,
    topSeller: 'Mango Madness',
    icon: '🥤',
  },
  {
    id: 'mr-oyster',
    name: 'Mr. Oyster',
    tagline: 'Pearl of the Sea',
    mascot: 'Sir Shellington',
    colors: ['#4682B4', '#5F9EA0'],
    revenue: '$567K',
    growth: 9,
    topSeller: 'Oyster Rockefeller',
    icon: '🦪',
  },
  {
    id: 'sweet-tooth',
    name: 'Sweet Tooth',
    tagline: 'Sugar Rush Central',
    mascot: 'Sweetness the Cupcake',
    colors: ['#FF69B4', '#FFB6C1'],
    revenue: '$234K',
    growth: 16,
    topSeller: 'Rainbow Explosion',
    icon: '🧁',
  },
];