export const BRANDS = [
  {
    id: 'angel-wings',
    name: 'Angel Wings',
    tagline: 'Wings. Shrimps. Fries. Respect the Basket.',
    mascot: 'Loudini the Wing Wizard',
    colors: ['#FFA500', '#FF6347'],
    revenue: '$0',
    growth: 0,
    topSeller: 'Angel Wings Basket',
    icon: '🍗',
  },
  {
    id: 'tha-morning-after',
    name: 'Tha Morning After',
    tagline: 'Breakfast that hits like a reset button.',
    mascot: 'Eggavier',
    colors: ['#FFD700', '#111111'],
    revenue: '$0',
    growth: 0,
    topSeller: 'Signature Breakfast Sandwich',
    icon: '🥪',
  },
  {
    id: 'espresso-co',
    name: 'Espresso Co.',
    tagline: 'Fuel for empires. Shots for champions.',
    mascot: 'Beanzo',
    colors: ['#2F1B0C', '#C9A227'],
    revenue: '$0',
    growth: 0,
    topSeller: 'Double Shot Espresso',
    icon: '☕️',
  },
  {
    id: 'mojo-juice',
    name: 'Mojo Juice',
    tagline: 'Fresh. Fast. Functional.',
    mascot: 'Mojo',
    colors: ['#00C853', '#00B0FF'],
    revenue: '$0',
    growth: 0,
    topSeller: 'Green Glow Smoothie',
    icon: '🥤',
  },
  {
    id: 'taco-yaki',
    name: 'Taco Yaki',
    tagline: 'Tacos meet hibachi — fire meets flavor.',
    mascot: 'Yaki',
    colors: ['#FF1744', '#FF9100'],
    revenue: '$0',
    growth: 0,
    topSeller: 'Fusion Taco Plate',
    icon: '🌮',
  },
  {
    id: 'sweet-tooth',
    name: 'Sweet Tooth',
    tagline: 'Desserts that don’t play.',
    mascot: 'Sugar',
    colors: ['#FF69B4', '#8A2BE2'],
    revenue: '$0',
    growth: 0,
    topSeller: 'Signature Dessert Cup',
    icon: '🍰',
  },
  {
    id: 'mr-oyster',
    name: 'Mr. Oyster',
    tagline: 'Oyster bar energy. Upscale flavor.',
    mascot: 'Mr. Oyster',
    colors: ['#0A2A43', '#D4AF37'],
    revenue: '$0',
    growth: 0,
    topSeller: 'Half Dozen Oysters',
    icon: '🦪',
  },
  {
    id: 'patty-daddy',
    name: 'Patty Daddy',
    tagline: 'The sauce is a secret. The flavor is not.',
    mascot: 'Paddy Daddy',
    colors: ['#8B4513', '#D2691E'],
    revenue: '$0',
    growth: 0,
    topSeller: 'Daddy Deluxe Burger',
    icon: '🍔',
  },
  {
    id: 'tossed',
    name: 'Tossed',
    tagline: 'Crisp bowls. Clean fuel. No excuses.',
    mascot: 'Toss',
    colors: ['#1B5E20', '#AEEA00'],
    revenue: '$0',
    growth: 0,
    topSeller: 'Build-Your-Own Salad',
    icon: '🥗',
  },
  {
    id: 'pasta-bish',
    name: 'Pasta Bish',
    tagline: 'Saucy. Bold. Built for cravings.',
    mascot: 'Bish',
    colors: ['#B71C1C', '#FFCCBC'],
    revenue: '$0',
    growth: 0,
    topSeller: 'Signature Pasta Bowl',
    icon: '🍝',
  },
];
