export const LOCATIONS = [
  {
    id: 'washington-parq',
    name: 'Washington Parq',
    x: '45%',
    y: '40%',
    status: 'surge' as const,
    revenue: '$678K',
    address: '1234 Main St, Washington DC',
  },
  {
    id: 'manhattan-central',
    name: 'Manhattan Central',
    x: '50%',
    y: '35%',
    status: 'open' as const,
    revenue: '$892K',
    address: '5678 Broadway, New York NY',
  },
  {
    id: 'chicago-loop',
    name: 'Chicago Loop',
    x: '40%',
    y: '38%',
    status: 'open' as const,
    revenue: '$456K',
    address: '910 Michigan Ave, Chicago IL',
  },
  {
    id: 'miami-beach',
    name: 'Miami Beach',
    x: '52%',
    y: '65%',
    status: 'maintenance' as const,
    revenue: '$234K',
    address: '321 Ocean Dr, Miami FL',
  },
  {
    id: 'los-angeles',
    name: 'Los Angeles',
    x: '15%',
    y: '55%',
    status: 'open' as const,
    revenue: '$567K',
    address: '789 Sunset Blvd, Los Angeles CA',
  },
  {
    id: 'seattle-downtown',
    name: 'Seattle Downtown',
    x: '12%',
    y: '25%',
    status: 'surge' as const,
    revenue: '$345K',
    address: '456 Pike St, Seattle WA',
  },
  {
    id: 'atlanta-midtown',
    name: 'Atlanta Midtown',
    x: '48%',
    y: '58%',
    status: 'open' as const,
    revenue: '$289K',
    address: '123 Peachtree St, Atlanta GA',
  },
  {
    id: 'boston-commons',
    name: 'Boston Commons',
    x: '55%',
    y: '32%',
    status: 'open' as const,
    revenue: '$412K',
    address: '789 Commonwealth Ave, Boston MA',
  },
];