export const LOCATIONS = [
  {
    id: 'atl-43-decatur',
    name: 'Atlanta – 43 Decatur St SE',
    x: '35%',
    y: '30%',
    status: 'open' as const,
    revenue: '$0',
    address: '43 Decatur St SE, Atlanta, GA 30303',
  },
  {
    id: 'atl-1650-virginia',
    name: 'Atlanta – 1650 Virginia Ave',
    x: '40%',
    y: '33%',
    status: 'open' as const,
    revenue: '$0',
    address: '1650 Virginia Ave, Atlanta, GA',
  },
  {
    id: 'atl-69-11th',
    name: 'Atlanta – 69 11th Street NW',
    x: '45%',
    y: '36%',
    status: 'open' as const,
    revenue: '$0',
    address: '69 11th Street NW, Atlanta, GA',
  },
  {
    id: 'atl-199-mitchell',
    name: 'Atlanta – 199 Mitchell St SW',
    x: '50%',
    y: '39%',
    status: 'open' as const,
    revenue: '$0',
    address: '199 Mitchell St SW, Atlanta, GA',
  },
  {
    id: 'dc-1355-u',
    name: 'Washington DC – 1355 U St NW',
    x: '55%',
    y: '42%',
    status: 'open' as const,
    revenue: '$0',
    address: '1355 U St NW, Washington, DC 20009',
  },
  {
    id: 'hou-2811-washington',
    name: 'Houston – 2811 Washington Ave',
    x: '60%',
    y: '45%',
    status: 'open' as const,
    revenue: '$0',
    address: '2811 Washington Ave, Houston, TX',
  },
  {
    id: 'atl-171-auburn',
    name: 'Atlanta – 171 Auburn Ave NE (Suite P)',
    x: '65%',
    y: '48%',
    status: 'open' as const,
    revenue: '$0',
    address: '171 Auburn Ave NE, Suite P, Atlanta, GA 30303',
  }
];
